export const ActionTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
  DELETE_ONE_PRODUCT: 'DELETE_ONE_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADD_FAVORITES: 'ADD_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'
}